## KNN Imputation
Reference: https://machinelearningmastery.com/knn-imputation-for-missing-values-in-machine-learning/ 


In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame
from sklearn.impute import KNNImputer

In [2]:
def missing(data):
    missing = data['Rainfall'].isnull().sum()
    percentage = missing/data.shape[0]*100
    print('Missing: %d \nPercentage: %.2f%%' % (missing, percentage))

In [5]:
df3 = pd.read_excel("GuaMusang_Kelantan.xlsx", parse_dates = ['Date'], na_values='?').iloc[:-192]
print('\n', df3)
missing(df3)


             Date  Rainfall
0     1982-01-01       3.0
1     1982-01-02       3.0
2     1982-01-03       3.0
3     1982-01-04       0.0
4     1982-01-05       0.0
...          ...       ...
14048 2020-06-18       0.0
14049 2020-06-19       0.0
14050 2020-06-20       0.2
14051 2020-06-21      25.8
14052 2020-06-22       0.2

[14053 rows x 2 columns]
Missing: 544 
Percentage: 3.87%


In [3]:
#Brook
df1 = pd.read_excel("Brook_Kelantan.xlsx", parse_dates = ['Date'], na_values='?')
print(df1)
missing(df1)

#Blau
df2 = pd.read_excel("Blau_Kelantan.xlsx", parse_dates = ['Date'], na_values='?')
print('\n', df2)
missing(df2)

#Gua Musang
df3 = pd.read_excel("GuaMusang_Kelantan.xlsx", parse_dates = ['Date'], na_values='?')
print('\n', df3)
missing(df3)

#GOB
df4 = pd.read_excel("GOB_Kelantan.xlsx", parse_dates = ['Date'], na_values='?')
print('\n', df4)
missing(df4)

#Balai Polis Bertam 
df5 = pd.read_excel("BalaiPolisBertam_Kelantan.xlsx", parse_dates = ['Date'], na_values='?')
print('\n', df5)
missing(df5)

#KGaring 
df6 = pd.read_excel("KGaring_Kelantan.xlsx", parse_dates = ['Date'], na_values='?')
print('\n', df6)
missing(df6)

            Date  Rainfall
0     1982-01-01       NaN
1     1982-01-02       NaN
2     1982-01-03       NaN
3     1982-01-04       NaN
4     1982-01-05       NaN
...          ...       ...
14240 2020-12-27       NaN
14241 2020-12-28       NaN
14242 2020-12-29       NaN
14243 2020-12-30       NaN
14244 2020-12-31       NaN

[14245 rows x 2 columns]
Missing: 1213 
Percentage: 8.52%

             Date  Rainfall
0     1982-01-01       NaN
1     1982-01-02       NaN
2     1982-01-03       NaN
3     1982-01-04       NaN
4     1982-01-05       NaN
...          ...       ...
14240 2020-12-27       NaN
14241 2020-12-28       NaN
14242 2020-12-29       NaN
14243 2020-12-30       NaN
14244 2020-12-31       NaN

[14245 rows x 2 columns]
Missing: 1340 
Percentage: 9.41%

             Date  Rainfall
0     1982-01-01       3.0
1     1982-01-02       3.0
2     1982-01-03       3.0
3     1982-01-04       0.0
4     1982-01-05       0.0
...          ...       ...
14240 2020-12-27       NaN
14241 2020-12-

In [4]:
date_col = df1['Date']

df = DataFrame()
df['Brook'] = df1['Rainfall'].values
df['Blau'] = df2['Rainfall'].values
df['Gua_Musang'] = df3['Rainfall'].values
df['GOB'] = df4['Rainfall'].values
df['BalaiPolisBertam'] = df5['Rainfall'].values
df['KGaring'] = df6['Rainfall'].values

print(df)

       Brook  Blau  Gua_Musang  GOB  BalaiPolisBertam  KGaring
0        NaN   NaN         3.0  NaN               NaN      0.0
1        NaN   NaN         3.0  NaN               NaN     10.0
2        NaN   NaN         3.0  NaN               NaN      0.0
3        NaN   NaN         0.0  NaN               NaN      0.0
4        NaN   NaN         0.0  NaN               NaN      0.0
...      ...   ...         ...  ...               ...      ...
14240    NaN   NaN         NaN  NaN               NaN      NaN
14241    NaN   NaN         NaN  NaN               NaN      NaN
14242    NaN   NaN         NaN  NaN               NaN      NaN
14243    NaN   NaN         NaN  NaN               NaN      NaN
14244    NaN   NaN         NaN  NaN               NaN      NaN

[14245 rows x 6 columns]


In [7]:
imputer = KNNImputer(n_neighbors = 5)
X = df.values

imputer.fit(X)
imputed_X = imputer.transform(X)

print(imputed_X)

[[ 3.1         0.          3.          2.5         9.5         0.        ]
 [ 6.5        10.3         3.          5.9         5.2        10.        ]
 [ 3.1         0.          3.          2.5         9.5         0.        ]
 ...
 [ 6.09074586  5.52935296  6.41343549  6.64979739  5.92652651  7.11300317]
 [ 6.09074586  5.52935296  6.41343549  6.64979739  5.92652651  7.11300317]
 [ 6.09074586  5.52935296  6.41343549  6.64979739  5.92652651  7.11300317]]


In [8]:
# create csv file for imputed Gua Musang rainfall data
df_GuaMusang = DataFrame(imputed_X[:,2], columns=['Rainfall'])
df_GuaMusang['Date'] = date_col.values
df_GuaMusang = df_GuaMusang[['Date','Rainfall']]
df_GuaMusang.to_csv('GuaMusang_imputed.csv', sep=',', index=False, float_format="%.1f")
print('\n', df_GuaMusang)
missing(df_GuaMusang)


             Date  Rainfall
0     1982-01-01  3.000000
1     1982-01-02  3.000000
2     1982-01-03  3.000000
3     1982-01-04  0.000000
4     1982-01-05  0.000000
...          ...       ...
14240 2020-12-27  6.413435
14241 2020-12-28  6.413435
14242 2020-12-29  6.413435
14243 2020-12-30  6.413435
14244 2020-12-31  6.413435

[14245 rows x 2 columns]
Missing: 0 
Percentage: 0.00%


In [7]:
df_Brook = DataFrame(imputed_X[:,0], columns=['Rainfall'])
df_Brook['Date'] = date_col.values
df_Brook = df_Brook[['Date','Rainfall']]
df_Brook.to_csv('Brook_imputed.csv', sep=',', index=False, float_format="%.1f")
print(df_Brook)
missing(df_Brook)

df_Blau = DataFrame(imputed_X[:,1], columns=['Rainfall'])
df_Blau['Date'] = date_col.values
df_Blau = df_Blau[['Date','Rainfall']]
df_Blau.to_csv('Blau_imputed.csv', sep=',', index=False, float_format="%.1f")
print('\n', df_Blau)
missing(df_Blau)

# create csv file for imputed Gua Musang rainfall data
df_GuaMusang = DataFrame(imputed_X[:,2], columns=['Rainfall'])
df_GuaMusang['Date'] = date_col.values
df_GuaMusang = df_GuaMusang[['Date','Rainfall']]
df_GuaMusang.to_csv('GuaMusang_imputed.csv', sep=',', index=False, float_format="%.1f")
print('\n', df_GuaMusang)
missing(df_GuaMusang)

df_GOB = DataFrame(imputed_X[:,3], columns=['Rainfall'])
df_GOB['Date'] = date_col.values
df_GOB = df_GOB[['Date','Rainfall']]
df_GOB.to_csv('GOB_imputed.csv', sep=',', index=False, float_format="%.1f")
print('\n', df_GOB)
missing(df_GOB)

df_BalaiPolisBertam = DataFrame(imputed_X[:,3], columns=['Rainfall'])
df_BalaiPolisBertam['Date'] = date_col.values
df_BalaiPolisBertam = df_BalaiPolisBertam[['Date','Rainfall']]
df_BalaiPolisBertam.to_csv('BalaiPolisBertam_imputed.csv', sep=',', index=False, float_format="%.1f")
print('\n', df_BalaiPolisBertam)
missing(df_BalaiPolisBertam)

df_KGaring = DataFrame(imputed_X[:,3], columns=['Rainfall'])
df_KGaring['Date'] = date_col.values
df_KGaring = df_KGaring[['Date','Rainfall']]
df_KGaring.to_csv('KGaring_imputed.csv', sep=',', index=False, float_format="%.1f")
print('\n', df_KGaring)
missing(df_KGaring)

            Date  Rainfall
0     1982-01-01  3.100000
1     1982-01-02  6.500000
2     1982-01-03  3.100000
3     1982-01-04  1.000000
4     1982-01-05  1.000000
...          ...       ...
14240 2020-12-27  6.090746
14241 2020-12-28  6.090746
14242 2020-12-29  6.090746
14243 2020-12-30  6.090746
14244 2020-12-31  6.090746

[14245 rows x 2 columns]
Missing: 0 
Percentage: 0.00%

             Date   Rainfall
0     1982-01-01   0.000000
1     1982-01-02  10.300000
2     1982-01-03   0.000000
3     1982-01-04   0.000000
4     1982-01-05   0.000000
...          ...        ...
14240 2020-12-27   5.529353
14241 2020-12-28   5.529353
14242 2020-12-29   5.529353
14243 2020-12-30   5.529353
14244 2020-12-31   5.529353

[14245 rows x 2 columns]
Missing: 0 
Percentage: 0.00%

        Rainfall       Date
0      3.000000 1982-01-01
1      3.000000 1982-01-02
2      3.000000 1982-01-03
3      0.000000 1982-01-04
4      0.000000 1982-01-05
...         ...        ...
14240  6.413435 2020-12-27
14241  6